version: '3'

services:
  laravel:
    container_name: laravel
    build:
      context: ./
      dockerfile: laravel.dockerfile
    image: laravel
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html
    networks:
      - la_network

  angular:
    container_name: angular
    build:
      context: ../frontend_angular
      dockerfile: angular.dockerfile
    volumes:
      - ../frontend_angular:/app:cached
    expose:
      - "80"
    restart: always
    ports:
      - "3000:3000"
    networks:
      - la_network
  db:
    image: mysql:8.1
    container_name: db
    volumes:
      - ../mysql:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravelBD
      MYSQL_USER: root1
      MYSQL_PASSWORD: root1
    networks:
      - la_network
  webserver:
    container_name: webserver
    depends_on:
      - laravel
      - angular
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - la_network

networks:
  la_network:
volumes:
  mysql: